// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/kackerx/kai/app/application"
	menu2 "github.com/kackerx/kai/app/domain/menu"
	user2 "github.com/kackerx/kai/app/domain/user"
	"github.com/kackerx/kai/app/infrastructure/menu"
	"github.com/kackerx/kai/app/infrastructure/menu/menuaction"
	"github.com/kackerx/kai/app/infrastructure/menu/menuactionresource"
	"github.com/kackerx/kai/app/infrastructure/rbac"
	"github.com/kackerx/kai/app/infrastructure/trans"
	"github.com/kackerx/kai/app/infrastructure/user"
	"github.com/kackerx/kai/app/infrastructure/user/role"
	"github.com/kackerx/kai/app/infrastructure/user/rolemenu"
	"github.com/kackerx/kai/app/infrastructure/user/userrole"
	"github.com/kackerx/kai/app/interfaces/api/handler"
	"github.com/kackerx/kai/app/interfaces/api/router"
	"github.com/kackerx/kai/injector/api"
)

import (
	_ "github.com/kackerx/kai/app/interfaces/api/swagger"
)

// Injectors from wire.go:

func BuildApiInjector() (*ApiInjector, func(), error) {
	repository, cleanup, err := api.InitAuth()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := InitGormDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	roleRepository := role.NewRepository(db)
	rolemenuRepository := rolemenu.NewRepository(db)
	menuactionresourceRepository := menuactionresource.NewRepository(db)
	userRepository := user.NewRepository(db)
	userroleRepository := userrole.NewRepository(db)
	rbacRepository := rbac.NewRepository(roleRepository, rolemenuRepository, menuactionresourceRepository, userRepository, userroleRepository)
	rbacAdapter := application.NewRbacAdapter(rbacRepository)
	syncedEnforcer, cleanup3, err := api.InitCasbin(rbacAdapter)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	service := user2.NewService(repository, userRepository, roleRepository, userroleRepository)
	menuRepository := menu.NewRepository(db)
	menuactionRepository := menuaction.NewRepository(db)
	login := application.NewLogin(repository, userRepository, roleRepository, userroleRepository, service, menuRepository, menuactionRepository, rolemenuRepository)
	handlerLogin := handler.NewLogin(login)
	transRepository := trans.NewRepository(db)
	menuService := menu2.NewService(transRepository, menuRepository, menuactionRepository, menuactionresourceRepository)
	applicationMenu := application.NewMenu(menuService)
	handlerMenu := handler.NewMenu(applicationMenu)
	applicationRole := application.NewRole(rbacAdapter, syncedEnforcer, transRepository, roleRepository, rolemenuRepository, userRepository)
	handlerRole := handler.NewRole(applicationRole)
	applicationUser := application.NewUser(repository, rbacAdapter, syncedEnforcer, transRepository, userRepository, userroleRepository, roleRepository)
	handlerUser := handler.NewUser(applicationUser)
	healthCheck := handler.NewHealthCheck()
	test := handler.NewTest()
	routerRouter := router.NewRouter(repository, syncedEnforcer, handlerLogin, handlerMenu, handlerRole, handlerUser, healthCheck, test)
	engine := api.InitGinEngine(routerRouter)
	seed := application.NewSeed(menuService, transRepository)
	apiInjector := NewApiInjector(engine, repository, syncedEnforcer, seed)
	return apiInjector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
