// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/kackerx/kai/app/application"
	"github.com/kackerx/kai/app/infrastructure/article"
	"github.com/kackerx/kai/app/interfaces/api/handler"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func BuildEngine() (*gin.Engine, *gorm.DB, func(), error) {
	db, cleanup, err := NewDB()
	if err != nil {
		return nil, nil, nil, err
	}
	repository := article.NewRepository(db)
	applicationArticle := application.NewArticle(repository)
	handlerArticle := handler.NewArticle(applicationArticle)
	router := InitRouter(handlerArticle)
	engine := InitGinEngine(router)
	return engine, db, func() {
		cleanup()
	}, nil
}

// wire.go:

var handlerSet = wire.NewSet(handler.NewArticle, handler.NewHealthCheck, handler.NewLogin, handler.NewMenu, handler.NewRole, handler.NewUser, handler.NewTest)

var appSet = wire.NewSet(application.NewArticle)

var repositorySet = wire.NewSet(article.NewRepository)
