// Code generated by MockGen. DO NOT EDIT.
// Source: app/application/login.go
//
// Generated by this command:
//
//	mockgen -source=app/application/login.go -destination=app/application/mock/login_gen.go -package=appmock
//

// Package appmock is a generated GoMock package.
package appmock

import (
	context "context"
	reflect "reflect"

	auth "github.com/kackerx/kai/app/domain/auth"
	menu "github.com/kackerx/kai/app/domain/menu"
	user "github.com/kackerx/kai/app/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockLogin is a mock of Login interface.
type MockLogin struct {
	ctrl     *gomock.Controller
	recorder *MockLoginMockRecorder
	isgomock struct{}
}

// MockLoginMockRecorder is the mock recorder for MockLogin.
type MockLoginMockRecorder struct {
	mock *MockLogin
}

// NewMockLogin creates a new mock instance.
func NewMockLogin(ctrl *gomock.Controller) *MockLogin {
	mock := &MockLogin{ctrl: ctrl}
	mock.recorder = &MockLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogin) EXPECT() *MockLoginMockRecorder {
	return m.recorder
}

// DestroyToken mocks base method.
func (m *MockLogin) DestroyToken(ctx context.Context, tokenString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyToken", ctx, tokenString)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyToken indicates an expected call of DestroyToken.
func (mr *MockLoginMockRecorder) DestroyToken(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyToken", reflect.TypeOf((*MockLogin)(nil).DestroyToken), ctx, tokenString)
}

// GenerateToken mocks base method.
func (m *MockLogin) GenerateToken(ctx context.Context, userID string) (*auth.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx, userID)
	ret0, _ := ret[0].(*auth.Auth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockLoginMockRecorder) GenerateToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockLogin)(nil).GenerateToken), ctx, userID)
}

// GetLoginInfo mocks base method.
func (m *MockLogin) GetLoginInfo(ctx context.Context, userID string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginInfo", ctx, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginInfo indicates an expected call of GetLoginInfo.
func (mr *MockLoginMockRecorder) GetLoginInfo(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginInfo", reflect.TypeOf((*MockLogin)(nil).GetLoginInfo), ctx, userID)
}

// QueryUserMenuTree mocks base method.
func (m *MockLogin) QueryUserMenuTree(ctx context.Context, userID string) (menu.Menus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUserMenuTree", ctx, userID)
	ret0, _ := ret[0].(menu.Menus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUserMenuTree indicates an expected call of QueryUserMenuTree.
func (mr *MockLoginMockRecorder) QueryUserMenuTree(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUserMenuTree", reflect.TypeOf((*MockLogin)(nil).QueryUserMenuTree), ctx, userID)
}

// UpdatePassword mocks base method.
func (m *MockLogin) UpdatePassword(ctx context.Context, userID, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockLoginMockRecorder) UpdatePassword(ctx, userID, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockLogin)(nil).UpdatePassword), ctx, userID, oldPassword, newPassword)
}

// Verify mocks base method.
func (m *MockLogin) Verify(ctx context.Context, userName, password string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, userName, password)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockLoginMockRecorder) Verify(ctx, userName, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockLogin)(nil).Verify), ctx, userName, password)
}
